//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Graph.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GRAPHTYPE                   129
#define IDR_NEWTYPE                     130
#define ID_MENUITEM32771                32771
#define ID_MENUITEM32772                32772
#define ID_MENUITEM32773                32773
#define ID_GRAPH_DATA1                  32774
#define ID_GRAPH_DATA2                  32775
#define ID_GRAPH_DATA3                  32776

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define DATANUM  10
#define DATAMAX  100

