//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tms.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TMS_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDC_EDITsno                     1000
#define IDC_EDITname                    1001
#define IDC_EDITsex                     1002
#define IDC_BUTTONtop                   1003
#define IDC_BUTTONpre                   1004
#define IDC_BUTTONnext                  1005
#define IDC_BUTTONbottom                1006
#define IDC_BUTTONedit                  1007
#define IDC_BUTTONadd                   1008
#define IDC_BUTTONdel                   1009
#define IDC_BUTTONrefresh               1010
#define IDC_EDITdpt                     1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
