//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OcxTest.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OCXTESTYPE                  129
#define IDD_GRID                        130
#define IDC_GRID                        1000
#define IDC_UPDATEVALUE                 1001
#define IDC_VALUE                       1002
#define ID_GridTest                     32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
