//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Top Studio.rc
//
#define IDI_TOPSTUDIO                   1
#define IDD_CUSTOM1                     129
#define IDC_EDIT_AUTHOR                 1000
#define IDC_EDIT_COMMENT                1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
