//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MFCexp10_5.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MFCEXPTYPE                  129
#define IDI_ICON1                       130
#define IDI_ICON3                       130
#define IDI_ICON2                       131
#define IDI_ICON4                       131
#define IDC_LISTVIEW                    132
#define ID_BIGICON                      133
#define ID_SMLICON                      134
#define ID_LIST                         135
#define ID_REPORT                       136

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
