//---------------------------------------------------------------------
// ¿…¶W : resource.h
//---------------------------------------------------------------------
#define IDM_NEW                         40001
#define IDM_OPEN                        40002
#define IDM_SAVE                        40003
#define IDM_SAVEAS                      40004
#define IDM_PRINT                       40005
#define IDM_PRINTSETUP                  40006
#define IDM_EXIT                        40007
#define IDM_UNDO                        40008
#define IDM_CUT                         40009
#define IDM_COPY                        40010
#define IDM_PASTE                       40011
#define IDM_LINK                        40012
#define IDM_LINKS                       40013
#define IDM_HELPCONTENTS                40014
#define IDM_HELPSEARCH                  40015
#define IDM_HELPHELP                    40016
#define IDM_ABOUT                       40017
