//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ComTest.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define CG_IDS_PHYSICAL_MEM             103
#define CG_IDS_DISK_SPACE               104
#define CG_IDS_DISK_SPACE_UNAVAIL       105
#define IDB_LIGHTBULB                   106
#define IDD_TIP                         107
#define CG_IDS_TIPOFTHEDAY              108
#define CG_IDS_TIPOFTHEDAYMENU          109
#define CG_IDS_DIDYOUKNOW               110
#define CG_IDS_FILE_ABSENT              111
#define CG_IDP_FILE_CORRUPT             112
#define CG_IDS_TIPOFTHEDAYHELP          113
#define IDR_MAINFRAME                   128
#define IDR_COMTESTYPE                  129
#define IDC_PHYSICAL_MEM                1000
#define IDC_BULB                        1000
#define IDC_DISK_SPACE                  1001
#define IDC_STARTUP                     1001
#define IDC_NEXTTIP                     1002
#define IDC_TIPSTRING                   1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
